### ISSUE TITLE
Libertine apps tend to flicker (from app color to black)

### ISSUE THREAD

**Issue by zubozrout** [ubports/libertine#58] opened 2019-08-14 05:58 UTC
- Device: Meizu MX4 (arale)
- Channel: edge
- Build: any

### Steps to reproduce
Run apps like Geany or Firefox in Libertine. If you click on menus etc the apps tend to flicker sometimes, making most areas black. There are however some lighter borders around texts and other edges visible so it is not a single black color.

Also, rotating the screen seems to have a positive effect on a black app (reverting it to normal) if you would like to see its latest state :).

### Expected behavior
Apps won't flicker.

### Actual behavior
Apps flicker when interacting with them.

**Comment by dobey** [comment] 2019-09-03 13:36
This sounds like a duplicate of ubports/libertine#10

**Comment by zubozrout** [comment] 2019-09-03 13:45
> This sounds like a duplicate of #10

I don't think so. This is not about menus being open in a new window. I believe that doesn't happen to me so it is ok on edge, but the app itself just goes all black (with some eges still being visible) from time to time. I can click on menus, icons or anything to trigger this behaviour (only happens sometimes), but it also does this on its own or when I rotate the screen for instance. Then another action makes it usually white again.

**Comment by UniversalSuperBox** [comment] 2021-06-08 16:49
Thanks for your report. This repository is moving to GitLab, and this issue has been filed there as https://gitlab.com/ubports/core/libertine/-/issues/58

**Closed as completed by UniversalSuperBox** 2021-06-08 16:49 UTC
