### ISSUE TITLE
Touchscreen in X.org applications does not work in landscape

### ISSUE THREAD

**Issue by tallero** [ubports/libertine#53] opened 2019-09-01 22:42 UTC
- Device: Hammerhead
- Channel: Stable
- Build: 16.04.2 LTS

### Steps to reproduce
- Setup a container
- Install a GTK application
- Open such application
- Rotate the phone
- Try to click on anything on the right side. 

### Expected behavior
- You should be able to interact with things on the screen

### Actual behavior
Input is being redirected on the other half of the screen.

### Logfiles and additional information
Made a [video](https://www.youtube.com/watch?v=uPo6Ntu6F7k) review.

EDIT: this seems the same as ubports/ubuntu-touch#975, since it seems to me that in libertine, when you tap the screen, an hidden mouse pointer is placed in the location on the tap and then it is left clicked.

**Comment by dobey** [comment] 2019-09-02 00:35
This is a duplicate of ubports/libertine#13

**Closed as completed** 2019-09-03 12:17 UTC
