### ISSUE TITLE
Touch input does not work in X.org dialog windows

### ISSUE THREAD

**Issue by tallero** [ubports/libertine#55] opened 2019-09-01 22:36 UTC
- Device: Hammerhead
- Channel: Stable
- Build: 16.04.2 LTS (?)

### Steps to reproduce
- Setup a container
- Install transmission
- Run transmission
- Try to click on "accept" in the disclaimer

In general just open a save dialog.

### Expected behavior
Touch input should be detected by the app. In particular, button tapping.

### Actual behavior
The window does not receive any input.

### Logfiles and additional information
Made a [video](https://www.youtube.com/watch?v=uPo6Ntu6F7k) review.
Do not know where to look for logs.

**Comment by dobey** [comment] 2019-09-02 00:42
This also appears to be a duplicate of ubports/libertine#13.

**Closed as completed by dobey** 2019-09-02 00:42 UTC

**Comment by tallero** [comment] 2019-09-02 06:16
> This also appears to be a duplicate of #13.

Wait, why is this a duplicate? This is about dialogs, not part of a full proper window. Also, it does not work on all of a dialog window, not only on one side, indepedently of the orientation.
